import type { Metadata } from 'next'
import { Inter, Merriweather_Sans, Lato, Source_Sans_3 } from 'next/font/google'

import '../styles/globals.css'
import { Header } from '@/components/header'
import { Providers } from './providers'
import { Footer } from '@/components/footer'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const merriweather = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-merriweather',
})
const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: ['100', '300', '700', '900'],
})

const source = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-source',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${lato.variable} ${source.variable} ${merriweather.variable} font-sans`}
    >
      <body>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  )
}
