import type { Metadata } from 'next'
import { Inter, Merriweather_Sans, Lato, Source_Sans_3 } from 'next/font/google'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const merriweather = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-merriweather',
})
const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: '700',
})

const source = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-source',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={
          (inter.className,
          merriweather.className,
          lato.className,
          source.className)
        }
      >
        {children}
      </body>
    </html>
  )
}
